spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3307/gulimall_pms
#    url: jdbc:mysql://192.168.1.122:3306/gulimall_pms
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: gulimall-product

mybatis-plus:
  mapper-location: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto

server:
  port: 10000

ssh:
#  enabled: false
  known_hosts: /Users/ryo/.ssh/known_hosts
  host: 127.0.0.1
  port: 22
  username: centos
  password: root
  forward:
    from_host: 127.0.0.1
    from_port: 3307
    to_host: 13.230.140.173
    to_port: 3306
#  ssh.enabled=false  # 是否启用 SSH 配置
#  ssh.host=127.0.0.1 # SSH 地址
#  ssh.port=22 # SSH 端口
#  ssh.username= # SSH 用户名
#  ssh.password= # SSH 密码
#  ssh.forward.from_host= # 绑定的本地地址
#  ssh.forward.from_port= # 绑定的本地端口
#  ssh.forward.to_host= # 正向代理的远程地址
#  ssh.forward.to_port= # 正向代理的远程端口
