spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.33.16:3306/gulimall_oms
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        secret-key: 127.0.0.1:8848
  application:
    name: gulimall-coupon

mybatis-plus:
  mapper-location: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto

server:
  port: 9000